<a href="https://colab.research.google.com/github/Aditya-sharma112245/MOVIE-RECOMMENDATION-SYSTEM/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [431]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import difflib

In [432]:
data=pd.read_csv('/content/movies.csv')

In [433]:
data.head()

index     budget  ...                                               crew           director
0      0  237000000  ...  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1      1  300000000  ...  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2      2  245000000  ...  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3      3  250000000  ...  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4      4  260000000  ...  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [434]:
data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [435]:
features = [
    'genres',               # High weight for genres
    'keywords',             # Moderate weight for keywords
    'overview',             # Moderate weight for overview
    'tagline',              # Low weight for tagline
    'cast',                 # High weight for cast
    'director',             # Low weight for director
    'production_companies',  # Moderate weight for production companies
    'production_countries',  # Moderate weight for production countries
    'runtime',              # Low weight for runtime
    'original_language',    # Low weight for original language
    'vote_average'          # Low weight for average rating
]


In [436]:
for f in features:
  data[f]=data[f].fillna('')

In [437]:
data['weighted_features'] = (
    data['genres'].fillna('').astype(str) * 5 + ' ' +  # High weight for genres
    data['keywords'].fillna('').astype(str) * 4 + ' ' + # Moderate weight for keywords
    data['overview'].fillna('').astype(str) * 4 + ' ' +  # Moderate weight for overview
    data['tagline'].fillna('') + ' ' +                   # Low weight for tagline
    data['cast'].fillna('').astype(str) * 4 + ' ' +     # High weight for cast
    data['director'].fillna('') + ' ' +                  # Low weight for director
    data['production_companies'].fillna('').astype(str) * 2 + ' ' +  # Moderate weight for production companies
    data['production_countries'].fillna('').astype(str) * 2 + ' ' +  # Moderate weight for production countries
    data['runtime'].fillna(0).astype(str) + ' ' +        # Low weight for runtime
    data['original_language'].fillna('').astype(str) + ' ' +  # Low weight for original language
    data['vote_average'].fillna(0).astype(str) + ' '      # Low weight for average rating
)



In [438]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['weighted_features'])

In [439]:
similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [440]:
print(similarity)

[[1.         0.04286905 0.03364283 ... 0.02769284 0.0202115  0.01313527]
 [0.04286905 1.         0.0352432  ... 0.04093122 0.02611576 0.02465761]
 [0.03364283 0.0352432  1.         ... 0.03132632 0.02218973 0.01685448]
 ...
 [0.02769284 0.04093122 0.03132632 ... 1.         0.04340672 0.02795793]
 [0.0202115  0.02611576 0.02218973 ... 0.04340672 1.         0.03596379]
 [0.01313527 0.02465761 0.01685448 ... 0.02795793 0.03596379 1.        ]]


In [441]:
ip=input('Enter movie name: ')

Enter movie name: hulk


In [442]:
list_of_all_movies=data['title'].tolist()

In [443]:
print(list_of_all_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [444]:
close_match=difflib.get_close_matches(ip,list_of_all_movies)

In [445]:
print(close_match)

['Hulk']


In [446]:
final_input=close_match[0]

In [447]:
idx=data[data['title']==final_input].index.values[0]

In [448]:
print(idx)

165


In [449]:
score_list=list(enumerate(similarity[idx]))

In [450]:
print(score_list)

[(0, 0.028500478085269343), (1, 0.015894301257153222), (2, 0.0330324999061512), (3, 0.017262845914674908), (4, 0.027770595445327693), (5, 0.044838698561709814), (6, 0.018666832951970462), (7, 0.03889290711676343), (8, 0.02791804694303885), (9, 0.022162317566790823), (10, 0.03659015262537325), (11, 0.022211161953438516), (12, 0.03127922003301444), (13, 0.020133263938080473), (14, 0.0549479035163989), (15, 0.019959409596806255), (16, 0.05042163352912251), (17, 0.05477861221877855), (18, 0.0749566382675816), (19, 0.014924268824702446), (20, 0.05049911878894509), (21, 0.03182218504058855), (22, 0.011648098146680053), (23, 0.05173413913662848), (24, 0.02602335140447813), (25, 0.012765865804426804), (26, 0.06857493356748151), (27, 0.04214054531266394), (28, 0.04561615585074878), (29, 0.017492622084393165), (30, 0.04708857492826206), (31, 0.04578634139175654), (32, 0.021684169815018917), (33, 0.06438805997915836), (34, 0.023554338425966638), (35, 0.07416317867171658), (36, 0.03363884094880683

In [451]:
sorted_list=sorted(score_list,key=lambda x:x[1],reverse=True)

In [452]:
print(sorted_list)

[(165, 1.0000000000000002), (174, 0.13142958646145395), (97, 0.12021532234234118), (1826, 0.11004920340501065), (189, 0.10818261432520901), (3580, 0.09736441780013716), (593, 0.09662292408396377), (1762, 0.09234219872005214), (1913, 0.09161391857122815), (1526, 0.09034475633832202), (1030, 0.0900283224288877), (421, 0.08904662501012865), (366, 0.08796749933917442), (953, 0.08735232730422447), (1241, 0.08554420908062982), (1920, 0.08548742894663763), (1200, 0.08420037367099979), (104, 0.08391602703905927), (1715, 0.08381189177132209), (43, 0.08371105257932517), (4724, 0.08317307719296464), (2157, 0.08251768603951702), (493, 0.08132288736939333), (2967, 0.08114509567955205), (4240, 0.08106016251559633), (490, 0.08054926505238627), (3014, 0.0804509652585119), (3472, 0.08008456462105665), (3821, 0.07934508210782001), (3311, 0.07882797247130303), (759, 0.07841660535433903), (4427, 0.0777900791108257), (46, 0.07689003492040541), (4401, 0.07639745755380227), (851, 0.07605840202825245), (511, 

In [453]:
ip=input('Enter movie name: ')
list_of_all_movies=data['title'].tolist()
close_match=difflib.get_close_matches(ip,list_of_all_movies)
final_input=close_match[0]
idx=data[data['title']==final_input].index.values[0]
score_list=list(enumerate(similarity[idx]))
sorted_list=sorted(score_list,key=lambda x:x[1],reverse=True)
print('MOVIES FOR YOU ARE - \n')
i=1
for m in sorted_list:
  index=m[0]
  fav=data[data.index==index]['title'].values[0]
  if(i<21):
    print(i,'.',fav)
    i+=1

Enter movie name: high school musical
MOVIES FOR YOU ARE - 

1 . High School Musical
2 . High School Musical 2
3 . High School Musical 3: Senior Year
4 . Bandslam
5 . 21 Jump Street
6 . Crossroads
7 . Love & Basketball
8 . 17 Again
9 . The DUFF
10 . Get Over It
11 . Not Another Teen Movie
12 . Across the Universe
13 . Thirteen
14 . Hamlet 2
15 . UnDivided
16 . Dancin' It's On
17 . Space Jam
18 . Coach Carter
19 . Alvin and the Chipmunks: The Squeakquel
20 . Brave New Girl
